model_name: "export/video_game/finetuned_verbalized_slots/t5-small_lr_2e-4_bs_32_wus_100_run1/epoch_10_step_160"
pretrained: True
lowercase: False
slot_name_conversion: "verbalize"
batch_size: 1
max_seq_length: 128
do_sample: True
#temperature: 1.0
top_p: 0.8
#top_k: 0
#no_repeat_ngram_size: 3
#repetition_penalty: 2.5
length_penalty: 1.0
num_return_sequences: 8
#semantic_decoding: True
#semantic_reranking: True
